name: CCFRAUD-une-partial
training_iters: 10000
validation:
  N_test: 85443
  N_train: 199364
batch_size: 256
random_seed: 0
is_data_aligned: True
models:
  gc_model:
    checkpoint_dir: /tmp/gc_model
    data_path: ~/files/ccfraud/dataset/Y_{}.pkl
    model_class: CCGCNet
    model_def_path: models.ccfraud_une_def
    model_path: null
    param:
      loss_fn: BCELoss
      model_args:
        D_in: 8
        D_out: 1
      optimizer:
        lr: 0.0001
        name: RMSprop
    ports:
      submodel0: 8600
      submodel1: 8601
      submodel2: 8602
  sub_models:
    submodel0:
      checkpoint_dir: /tmp/submodel0
      data_path: ~/files/ccfraud/dataset/X_{}_0.pkl
      model_class: FourLayerNet
      model_def_path: models.ccfraud_une_def
      model_path: null
      param:
        model_args:
          D_in: 10
          H_1: 5
          H_2: 6
          H_3: 7
          H_4: 8
        optimizer:
          lr: 0.0001
          name: RMSprop
allocations:
  gc_model: ba
  trusted_party: ba
  submodel0: ba
  submodel1: i1
  submodel2: i2
trusted_party:
  tp_class: UnsecureTP
  tp_def_path: net_layers
  ports:
    gc_model: 8800
    submodel0: 8700
    submodel1: 8701
    submodel2: 8702
  param: {}
hosts:
  ba:
    ports:
      alignment: 8500
    conn_param:
      host: "localhost"
      user: "Eric_Vader"
      connect_kwargs:
        key_filename: "./ssh_keys/ba.key"
  i1:
    ports:
      alignment: 8501
    conn_param:
      host: "localhost"
      user: "Eric_Vader"
      connect_kwargs:
        key_filename: "./ssh_keys/i1.key"
  i2:
    ports:
      alignment: 8502
    conn_param:
      host: "localhost"
      user: "Eric_Vader"
      connect_kwargs:
        key_filename: "./ssh_keys/i2.key"
mlflow:
  preamble: ulimit -Sn 65536; source /etc/profile; conda activate cs6203;
  mlflow_run: mlflow run /home/Eric_Vader/Workspace/CS6203_proj -P encoded_config="{encoded_config}"
